site_name: SolarNode Handbook

theme:
    name: material
    logo: images/logo.png
    features:
        - content.code.annotate
        - content.code.copy
        - navigation.instant
        - navigation.tracking
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: amber
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: amber
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

extra_css:
  - css/sn.css

plugins:
    - awesome-pages:
        collapse_single_pages: true
    - enumerate-headings
    - open-in-new-tab
    - search:
        lang: en

markdown_extensions:

    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true

    # Python Markdown Extensions
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
